### ISSUE TITLE
Error message on Cloud Run deployment

### ISSUE THREAD

**Issue by sgibson91** [sgibson91/binderhub-deploy-gke#18]
```
Error: failed to deploy to Cloud Run: exit status 1. output:
Deploying container to Cloud Run service [binderhub-deploy-gke] in project [binder-sandbox-194621] region [europe-west1]
Deploying new service...
Setting IAM Policy..............done
Creating Revision.................................................................................................................................................
....................................................................................................................................failed
Deployment failed
ERROR: (gcloud.beta.run.deploy) Cloud Run error: Container failed to start. Failed to start and then listen on the port defined by the PORT environment variable. 
Logs for this revision might contain more information.
```

**Comment by minrk** [comment]
I might know what this is. Cloud Run containers [**must** listen for HTTP requests on $PORT](https://cloud.google.com/run/docs/developing#code_requirements).

(copying from gitter) I think what we may want is to use [open-in-cloud-shell](https://cloud.google.com/shell/docs/open-in-cloud-shell) instead of Cloud Run Button, since GCP has a mechanism for deploying scripts in the cloud shell environment, we can skip trying to run it in a service container like Cloud Run.

**Comment by sgibson91** [comment]
related #21

**Comment by makquel** [comment]
Any progress on solving this issue?

**Comment by sgibson91** [comment]
Hi! Unfortunately not, I haven't been able to dedicate much time to this project since I did some work to deploy the infrastructure using terraform last year. Currently, the repo doesn't support a "one-click deployment" option, instead either [the scripts can be run locally](https://github.com/alan-turing-institute/binderhub-deploy-gke#children_crossing-usage) or [pull the Docker container and execute that locally](https://github.com/alan-turing-institute/binderhub-deploy-gke#house_with_garden-running-the-container-locally). Hopefully I can find some time to prioritise looking into `open-in-cloud-shell` as a "one-click deployment" option in the future.
